services:
  mysql:
    image: mysql:8.0
    container-name: microservices-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes: -mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: "--default-authentication-plugin=mysql_native_password"
    healthcheck:
      test: ["cmd", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - microservices-network

  user-service:
    build:
      context: ../module2-user-service
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      SPRING_PROFILES_ACTIVES: dockerfile
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: users
      DB_USER: root
      DB_PASSWORD: Root
      JAVA_OPTS: "-Xmx256m -Xms128m"
    ports:
      - "8081:8080"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-q",
          "--spider",
          "http://localhost:8080/actuator/health",
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - microservices-network
    deploy:
      ressources:
        limits:
          memory: 384M
          cpus: "0.5"

  order-service:
    build:
      context: ../Module3
      dockerfile: Dockerfile
    container_name: order-service
    environment:
      SPRING_PROFILES_ACTIVES: dockerfile
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: users
      DB_USER: root
      DB_PASSWORD: Root
      JAVA_OPTS: "-Xmx256m -Xms128m"
    ports:
      - "8082:8080"
    depends_on:
      mysql:
        condition: service_healthy
      user-service:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-q",
          "--spider",
          "http://localhost:8080/actuator/health",
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - microservices-network
    deploy:
      ressources:
        limits:
          memory: 384M
          cpus: "0.5"

volumes:
  mysql-data:

networks:
  microservices-network:
    driver: bridge
